#!/bin/bash -ex
# alternative to terraform apply (which will do the zip etc)
# quicker and does pre-check compile

# the favicon is made with base64 tick.png > cv/favicon.png64
#env=${1:-dev}
#export AWS_PROFILE=bmj-$env

pushd cv
if ! python -m py_compile *.py; then
    echo "not updating"
    
    exit
else
  rm -rf cv/__pycache__
fi


# create zip file
if [ -e ../cv.zip ]; then
  rm ../cv.zip
fi

#pushd terraform
#terraform output -no-color > ../terraform_output.py
#popd

zip ../cv.zip *.py *.html *.png64
popd
# update lambda function
aws lambda update-function-code --zip-file fileb://$PWD/cv.zip  --function-name cv-experimental | grep CodeSize

